name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: python:3.9

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PlatformIO dependency
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Build the embedded application (main.cpp)
        run: make build

  unittest:
    runs-on: ubuntu-latest

    container:
      image: python:3.9

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PlatformIO dependency
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          pio platform install native

      - name: Run unittests
        run: make tests

  linting:
    runs-on: ubuntu-latest

    container:
      image: python:3.9

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify codebase linting
        run: make format-check
